// This file is replaced with actual data during SCORM package generation.
// The variable MODULE_DATA will contain the JSON generated by Claude API.
var MODULE_DATA = {
  "title": "Module de démonstration",
  "language": "fr",
  "summary": {
    "chapters": [
      {
        "title": "Chapitre 1 : Introduction",
        "sections": [
          {
            "title": "Présentation générale",
            "content": "Ceci est un module de démonstration. Le contenu sera généré automatiquement à partir de votre document de cours."
          }
        ]
      }
    ]
  },
  "glossary": [
    { "term": "Terme exemple", "definition": "Définition de démonstration." }
  ],
  "flashcards": [
    { "type": "concept", "front": "Concept exemple", "back": "Définition du concept." }
  ],
  "quiz": [
    {
      "question": "Ceci est une question de démonstration ?",
      "choices": ["Choix A", "Choix B", "Choix C", "Choix D"],
      "correct": 0,
      "explanation": "Le choix A est correct car ceci est un exemple."
    }
  ]
};
